cc = g++

1: knapsack.cpp
	$(cc) -O knapsack.cpp -o knapsack

1LH: knapsack_LH.cpp
	$(cc) -O knapsack_LH.cpp -o knapsack_LH

2: LICS.cpp
	$(cc) -O LICS.cpp -o LICS

3: localAlignment.cpp
	$(cc) -O localAlignment.cpp -o localAlignment

4: partialHMM.cpp
	$(cc) -O partialHMM.cpp -o partialHMM
